-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_1
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_1` DEFAULT CHARACTER SET utf8 ;
USE `db_1` ;

-- -----------------------------------------------------
-- Table `db_1`.`all`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_1`.`all` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `composition` VARCHAR(255) NOT NULL,
  `artist` VARCHAR(255) NOT NULL,
  `date` INT NOT NULL,
  `album` VARCHAR(255) NOT NULL,
  `genre` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `db_1`.`all`
-- -----------------------------------------------------
START TRANSACTION;
USE `db_1`;
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Smells Like Teen Spirit', 'Nirvana', 1991, 'Nevermind', 'Grunge');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Love Will Tear Us Apart', 'Joy Division', 1980, 'Substance', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'I Feel Love', 'Донна Саммер', 1977, 'I Remember Yesterday', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'How Soon Is Now?', 'The Smiths', 1985, 'Hatful of Hollow', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Last Nite', 'The Strokes', 2001, 'Is This It', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Common People', 'Pulp', 1995, 'Different Class', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'I Bet You Look Good on the Dancefloor', 'Arctic Monkeys', 2005, 'Whatever People Say I Am, That’s What I’m Not', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Blue Monday', 'New Order', 1983, 'Substance', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Be My Baby', 'The Ronettes', 1963, 'Presenting the Fabulous Ronettes', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Good Vibrations', 'The Beach Boys', 1966, 'Smiley Smile', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Eleanor Rigby', 'The Beatles', 1966, 'Revolver', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'There Is a Light That Never Goes Out', 'The Smiths', 1986, 'The Queen Is Dead', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Live Forever', 'Oasis', 1994, 'Definitely Maybe', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'God Only Knows', 'The Beach Boys', 1966, 'Pet Sounds', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Heroes', 'Дэвид Боуи', 1977, 'Heroes', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Seven Nation Army', 'The White Stripes', 2003, 'Elephant', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'A Day in the Life', 'The Beatles', 1967, 'Sgt. Pepper’s Lonely Hearts Club Band', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Hey Ya!', 'OutKast', 2003, 'Speakerboxxx/The Love Below', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Heart of Glass', 'Blondie', 1979, 'Parallel Lines', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Girls & Boys', 'Blur', 1995, 'Parklife', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Ghost Town', 'The Specials', 1981, 'The Singles Collection', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'There She Goes', 'The La’s', 1988, 'The La’s', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Waterloo Sunset', 'The Kinks', 1967, 'Something Else by The Kinks', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Hurricane', 'Боб Дилан', 1975, 'Desire', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Wake Up', 'Arcade Fire', 2005, 'Funeral', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Losing My Edge', 'LCD Soundsystem', 2002, 'LCD Soundsystem', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'God Save the Queen', 'Sex Pistols', 1977, 'Never Mind the Bollocks, Here’s the Sex Pistols', 'Rock');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Time for Heroes', 'The Libertines', 2003, 'Up the Bracket', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Gimme Shelter', 'The Rolling Stones', 1969, 'Let It Bleed', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Once in a Lifetime', 'Talking Heads', 1980, 'Remain in Light', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Fools Gold', 'The Stone Roses', 1989, 'The Stone Roses', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'London Calling', 'The Clash', 1979, 'London Calling', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Animal Nitrate', 'Suede', 1993, 'Suede', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Life on Mars?', 'Дэвид Боуи', 1971, 'Hunky Dory', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Strawberry Fields Forever', 'The Beatles', 1967, 'Magical Mystery Tour', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Wonderwall', 'Oasis', 1995, '(What’s the Story) Morning Glory?', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'River Deep, Mountain High', 'Айк и Тина Тёрнеры', 1966, 'River Deep Mountain High', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Nothing Compares 2 U', 'Шинейд О’Коннор', 1990, 'I Do Not Want What I Haven’t Got', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Maps', 'Yeah Yeah Yeahs', 2003, 'Fever to Hell', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, '99 Problems', 'Jay-Z', 2004, 'The Black Album', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Back to Black', 'Эми Уайнхаус', 2006, 'Back to Black', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'The Universal', 'Blur', 1995, 'The Great Escape', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'A Design for Life', 'Manic Street Preachers', 1996, 'Everything Must Go', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Debaser', 'Pixies', 1989, 'Doolittle', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Paranoid Android', 'Radiohead', 1997, 'OK Computer', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'I Heard It Through the Grapevine', 'Марвин Гэй', 1968, 'In the Groove', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Like a Prayer', 'Мадонна', 1989, 'Like a Prayer', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Boys Don’t Cry', 'The Cure', 1979, 'Boys Don’t Cry', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Like a Rolling Stone', 'Боб Дилан', 1965, 'Highway 61 Revisited', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Walk on the Wild Side', 'Лу Рид', 1972, 'Transformer', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Ashes to Ashes', 'Дэвид Боуи', 1980, 'Scary Monsters (and Super Creeps)', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'One More Time', 'Daft Punk', 2000, 'Discovery', 'Electronic');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Paper Planes', 'M.I.A.', 2008, 'Kala', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Born to Run', 'Брюс Спрингстин', 1975, 'Born to Run', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'The Model', 'Kraftwerk', 1981, 'The Man-Machine', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Sabotage', 'Beastie Boys', 1994, 'Ill Comunication', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Billie Jean', 'Майкл Джексон', 1982, 'Thriller', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Suspicious Minds', 'Элвис Пресли', 1968, 'Elvis in Person at the International Hotel', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Loaded', 'Primal Scream', 1990, 'Screamadelica', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Babies', 'Pulp', 1992, 'His ’n’ Hers', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'True Faith', 'New Order', 1987, 'Substance', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Young Americans', 'Дэвид Боуи', 1975, 'Young Americans', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Unfinished Sympathy', 'Massive Attack', 1991, 'Blue Lines', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'This Charming Man', 'The Smiths', 1983, 'Best...I', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Stand by Me', 'Бен Э. Кинг', 1961, 'Don’t Play That Song!', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Straight Outta Compton', 'N.W.A', 1988, 'Straight Outta Compton', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Cigarettes & Alcohol', 'Oasis', 1994, 'Definitely Maybe', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Blackbird', 'The Beatles', 1968, 'The Beatles', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, '(White Man) In Hammersmith Palais', 'The Clash', 1978, 'The Story of the Clash, Volume 1', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'My Generation', 'The Who', 1965, 'My Generation', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Ever Fallen in Love (With Someone You Shouldn’t’ve)', 'Buzzcocks', 1978, 'Love Bites', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Venus in Furs', 'The Velvet Underground', 1967, 'The Velvet Underground & Nico', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Sheela-Na-Gig', 'Пи Джей Харви', 1991, 'Dry', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Take Me Out', 'Franz Ferdinand', 2004, 'Franz Ferdinand', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Dry Your Eyes', 'The Streets', 2004, 'A Grand Don’t Come for Free', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Wuthering Heights', 'Кейт Буш', 1978, 'The Kick Inside', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Hey Jude', 'The Beatles', 1968, '19671970', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Into My Arms', 'Nick Cave and the Bad Seeds', 1997, 'The Boatman’s Call', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Fell in Love With a Girl', 'The White Stripes', 2002, 'White Blood Cells', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Taxman', 'The Beatles', 1966, 'Revolver', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Niggas in Paris', 'Jay-Z и Канье Уэст', 2011, 'Watch the Throne', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Crazy in Love', 'Бейонсе', 2003, 'Dangerously in Love', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Complete Control', 'The Clash', 1977, 'The Story of the Clash, Volume 1', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Anarchy in the U.K.', 'Sex Pistols', 1976, 'Never Mind the Bollocks, Here’s the Sex Pistols', 'Rock');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Every Day Is Like a Sunday', 'Моррисси', 1988, 'Viva Hate', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Get Ur Freak On', 'Мисси Эллиотт', 2001, 'Miss E... So Addictive', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Video Games', 'Лана Дель Рей', 2011, 'Born to Die', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Lose Yourself', 'Эминем', 2002, 'Music from and Inspired by the Motion Picture 8 Mile', 'Rap');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Hallelujah', 'Джеф Бакли', 1994, 'Grace', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Time to Pretend', 'MGMT', 2008, 'Oracular Spectacular', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'All My Friends', 'LCD Soundsystem', 2007, 'Sound of Silver', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Toxic', 'Бритни Спирс', 2004, 'In the Zone', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Gold Digger', 'Канье Уэст', 2005, 'Late Registration', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Do You Realize??', 'The Flaming Lips', 2002, 'Yoshimi Battles the Pink Robots', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Fight the Power', 'Public Enemy', 1989, 'Fear of a Black Planet', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'What a Waster', 'The Libertines', 2002, 'Up the Bracket', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'The Message', 'Grandmaster Flash and the Furious Five', 1982, 'The Message', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Killing in the Name', 'Rage Against the Machine', 1992, 'Rage Against the Machine', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'No One Knows', 'Queens of the Stone Age', 2002, 'Songs for the Deaf', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'I Am the Resurrection', 'The Stone Roses', 1989, 'The Stone Roses', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Losing My Religion', 'R.E.M.', 1991, 'Out of Time', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Motorcycle Emptiness', 'Manic Street Preachers', 1992, 'Generation Terrorists', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Superstition', 'Стиви Уандер', 1972, 'Talking Book', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'The Drowners', 'Suede', 1993, 'Suede', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Song 2', 'Blur', 1997, 'Blur', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Don’t Look Back in Anger', 'Oasis', 1995, '(What’s the Story) Morning Glory?', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'House of Jealous Lovers', 'The Rapture', 2002, 'Echoes', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Running Up That Hill', 'Кейт Буш', 1985, 'House of Love', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Standing in the Way of Control', 'The Gossip', 2006, 'Standing in the Way of Control', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Ice Hockey Hair', 'Super Furry Animals', 1998, 'Ice Hockey Hair', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Rescue Me', 'Фонтелла Басс', 1965, 'The New Look', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Supersonic', 'Oasis', 1994, 'Definitely Maybe', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'When Doves Cry', 'Принс', 1984, 'Purple Rain', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Step On', 'Happy Mondays', 1990, 'Pills \'n\' Thrills and Bellyaches', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Bitter Sweet Symphony', 'The Verve', 1997, 'Urban Hymns', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Mr. Brightside', 'The Killers', 2003, 'Hot Fuss', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Geno', 'Dexys Midnight Runners', 1980, 'Searching for the Young Soul Rebels', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Someday', 'The Strokes', 2002, 'Is This It', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Waterfall', 'The Stone Roses', 1991, 'The Stone Roses', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Virginia Plain', 'Roxy Music', 1972, 'Greatest Hits', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Celebrity Skin', 'Hole', 1998, 'Celebrity Skin', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Hotel Yorba', 'The White Stripes', 2001, 'White Blood Cells', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Purple Rain', 'Принс', 1984, 'Purple Rain', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Teenage Kicks', 'The Undertones', 1977, 'The Undertones', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Disco 2000', 'Pulp', 1995, 'Different Class', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Just Like Honey', 'The Jesus and Mary Chain', 1985, 'Psychocandy', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Regulate', 'Warren G при участии Nate Dogg', 1994, 'Regulate..G Funk Era', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'The Eton Rifles', 'The Jam', 1979, 'Setting Sons', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'A Change Is Gonna Come', 'Сэм Кук', 1964, 'Ain’t That Good News', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Wichita Lineman', 'Глен Кэмпбелл', 1968, 'Wichita Lineman', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Jumpin’ Jack Flash', 'The Rolling Stones', 1968, 'Through the Past, Darkly (Big Hits Vol. 2)', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Pretty Vacant', 'Sex Pistols', 1977, 'Never Mind the Bollocks, Here’s the Sex Pistols', 'Rock');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Gigantic', 'Pixies', 1988, 'Surfer Rosa', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Over and Over', 'Hot Chip', 2006, 'The Warning', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'The Only One I Know', 'The Charlatans', 1990, 'Some Friendly', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Paint It, Black', 'The Rolling Stones', 1966, 'Aftermath', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Men’s Needs', 'The Cribs', 2007, 'Men’s Needs, Women’s Need, Whatever', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Monster', 'Канье Уэст при участии Jay-Z, Ники Минаж и Bon Iver', 2010, 'My Beautiful Dark Twisted Fantasy', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'No Woman, No Cry', 'Bob Marley & the Wailers', 1974, 'Natty Dread', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Windowlicker', 'Aphex Twin', 1999, '26 Mixes for Cash', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Alone Again Or', 'Love', 1967, 'Forever Changes', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Creep', 'Radiohead', 1992, 'Pablo Honey', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Hello Goodbye', 'The Beatles', 1967, 'Magical Mystery Tour', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Atomic', 'Blondie', 1980, 'Eat to the Beat', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Some Velvet Morning', 'Нэнси Синатра и Ли Хэзлвуд', 1967, 'Moving with Nancy', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Soon', 'My Bloody Valentine', 1991, 'Loveless', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Number 9 Dream', 'Джон Леннон', 1974, 'Walls and Bridges', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'West End Girls', 'Pet Shop Boys', 1984, 'Please', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'All the Young Dudes', 'Mott the Hoople', 1972, 'All the Young Dudes', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, '(Sittin’ on) The Dock of the Bay', 'Отис Реддинг', 1972, 'The Dock of the Bay', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Follow the Leader', 'Eric B. & Rakim', 1988, 'Follow the Leader', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Dancing in the Street', 'Martha and the Vandellas', 1964, 'Dance Party', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Freak Scene', 'Dinosaur Jr.', 1988, 'Bug', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Papa’s Got a Brand New Bag', 'Джеймс Браун', 1965, 'Papa’s Got a Brand New Bag', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Ace of Spades', 'Motorhead', 1980, 'Ace of Spades', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'I Want to Hold Your Hand', 'The Beatles', 1963, 'The Beatles’ Long Sally', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Louie Louie', 'The Kingsmen', 1963, 'The Kingsmen in Prison', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Tiny Dancer', 'Элтон Джон', 1972, 'Madman Across the Water', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Purple Haze', 'The Jimi Hendrix Experience', 1967, 'Are You Experienced', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Transmission', 'Joy Division', 1979, 'Substance', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Son of a Preacher Man', 'Дасти Спрингфилд', 1968, 'Dusty in Memphis', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Changes', 'Дэвид Боуи', 1972, 'Hunky Dory', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'I Want You Back', 'The Jackson 5', 1969, 'Diana Rose Presents The Jackson 5', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Fix Up, Look Sharp', 'Диззи Раскал', 2002, 'Boy in da Corner', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Cannonball', 'The Breeders', 1993, 'Last Splash', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, '(You Gotta) Fight for Your Right (To Party!)', 'Beastie Boys', 1987, 'Licensed to Ill', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Temporary Secretary', 'Пол Маккартни', 1980, 'McCartney II', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Daniel', 'Bat for Lashes', 2009, 'Two Suns', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Green Onions', 'Booker T. & the M.G.’s', 1962, 'Green Onions', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Higher Than the Sun', 'Primal Scream', 1991, 'Screamadelica', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'A-Punk', 'Vampire Weekend', 2007, 'Vampire Weekend', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Someone Great', 'LCD Soundsystem', 2007, 'Sound of Silver', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Rebel Without a Pause', 'Public Enemy', 1987, 'It Takes a Nation of Millions to Hold Us Back', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Yes', 'McAlmont & Butler', 1995, 'The Sound of McAlmont & Butler', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Won’t Get Fooled Again', 'The Who', 1971, 'Who’s Next', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Can’t Stand Me Now', 'The Libertines', 2004, 'The Libertines', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Roll Over Beethoven', 'Чак Берри', 1956, 'Rock, Rock, Rock', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'The Tracks of My Tears', 'The Miracles', 1965, 'Going to a Go-Go', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Never Understand', 'The Jesus and Mary Chain', 1985, 'Psychocandy', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Shake Some Action', 'Flamin’ Groovies', 1976, 'Shake Some Action', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Protect Ya Neck', 'Wu-Tang Clan', 1993, 'Enter the Wu-Tang Clan (36 chambers)', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'I Can See for Miles', 'The Who', 1967, 'The Who Sell Out', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'No Good (Start the Dance)', 'The Prodigy', 1994, 'Music for the Jilted Generation', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Under Pressure', 'Queen и Дэвид Боуи', 1981, 'Hot Space', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'There Goes the Fear', 'Doves', 2002, 'The Last Broadcast', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Subterranean Homesick Blues', 'Боб Дилан', 1965, 'Bringing It All Back Home', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'The Concept', 'Teenage Fanclub', 1991, 'Bandwagonesque', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Murdy Bum', 'Arctic Monkeys', 2006, 'Whatever People Say I Am, That’s What I’m Not', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Don’t Look Back into the Sun', 'The Libertines', 2004, '', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Shoot Speed/Kill Light', 'Primal Scream', 2000, 'XTRMNTR', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Nowhere to Run', 'Martha and the Vandellas', 1965, 'Dance Party', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Sign o’ the Times', 'Принс', 1987, 'Sign o’ the Times', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Tender', 'Blur', 1999, '13', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Alright', 'Supergrass', 1995, 'I Should Coco', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Atmosphere', 'Joy Division', 1980, 'Substance', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Made of Stone', 'The Stone Roses', 1989, 'The Stone Roses', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Monkey Gone to Heaven', 'Pixies', 1988, 'Doolittle', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'This Is a Low', 'Blur', 1994, 'Parklife', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Light My Fire', 'The Doors', 1967, 'The Doors', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Where Is My Mind?', 'Pixies', 1988, 'Surfer Rosa', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'I’m Waiting for the Man', 'The Velvet Underground', 1967, 'The Velvet Underground & Nico', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'What’s Going On', 'Марвин Гэй', 1971, 'What’s Going On', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Crazy', 'Пэтси Клайн', 1961, 'Patsy Cline Showcase', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Fairytale of New York', 'The Pogues при участии Кирсти Маккол', 1987, 'If I Should Fall from Grace with God', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Reptilia', 'The Strokes', 2004, 'Room of Fire', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Rise', 'Public Image Ltd', 1986, 'Album', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Levi Stabbs’ Tears', 'Билли Брэгг', 1986, 'Talking with the Taxman about Poetry', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Da Funk', 'Daft Punk', 1995, 'Homework', 'Electronic');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Jealous Guy', 'Джон Леннон', 1971, 'Imagine', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Hit the North', 'The Fall', 1987, 'Seminal Live', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'You Keep Me Hangin’ On', 'The Supremes', 1966, 'The Supremes Sing Holland-Dozier-Holland', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Radio Free Europe', 'R.E.M.', 1981, 'Murmur', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Here Comes Your Man', 'Pixies', 1989, 'Doolittle', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Solsbury Hill', 'Питер Гэбриэл', 1977, 'Peter Gabriel', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Lithium', 'Nirvana', 1991, 'Nevermind', 'Grunge');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Lithium', 'Nirvana', 1991, 'Nevermind', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Rip It Up', 'Orange Juice', 1983, 'Rip It Up', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Faster', 'Manic Street Preachers', 1994, 'The Holy Bible', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Straight to You', 'Nick Cave and the Bad Seeds', 1992, 'Henry’s Dream', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'You Really Got Me', 'The Kinks', 1964, 'Kinks', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'End of a Century', 'Blur', 1994, 'Parklife', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Mrs. Robinson', 'Simon & Garfunkel', 1968, 'Bookends', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Golden Skans', 'Klaxons', 2007, 'Myths of the Near Future', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Electicity', 'Spiritualized', 1995, 'Ladies and Gentlemen We Are Floating in Space', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Birthday', 'The Sugarcubes', 1987, 'Life’s Too Good', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Get Up (I Feel Like Being a) Sex Machine', 'Джеймс Браун', 1970, 'Sex Machine', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Respect', 'Арета Франклин', 1967, 'I Never Loved a Man the Way I Love You', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Sympathy for the Devil', 'The Rolling Stones', 1968, 'Beggars Banquet', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Temptation', 'New Order', 1983, 'Substance', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Oblivion', 'Граймс', 2012, 'Visions', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Ms. Jackson', 'OutKast', 2001, 'Stankonia', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Do I Wanna Know?', 'Arctic Monkeys', 2013, 'AM', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, '(Don’t Fear) The Reaper', 'Blue Öyster Cult', 1976, 'Agents of Fortune', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Get It On', 'T. Rex', 1971, 'Electric Warrior', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Psycho Killer', 'Talking Heads', 1977, 'Talking Heads: 77', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Jailhouse Rock', 'Элвис Пресли', 1957, 'Jailhouse Rock', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'In Between Days', 'The Cure', 1985, 'The Head on the Door', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Blitzkrieg Bop', 'The Ramones', 1976, 'Ramones', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Tupelo', 'Nick Cave and the Bad Seeds', 1985, 'The Firstborn Is Dead', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Whatever', 'Oasis', 1994, 'Definitely Maybe', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Rent', 'Pet Shop Boys', 1987, 'Actually', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Sour Times', 'Portishead', 1994, 'Dummy', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Public Image', 'Public Image Ltd', 1978, 'First Issue', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Dry the Rain', 'The Beta Band', 1997, 'Champion Versions', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Motown Junk', 'Manic Street Preachers', 1991, 'Forever Delayed', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Fuck Forever', 'Babyshambles', 2005, 'Down in Albion', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Voodoo Child (Slight Return)', 'The Jimi Hendrix Experience', 1968, 'Electric Ladyland', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Intergalactic', 'Beastie Boys', 1998, 'Hello Nasty', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'My Girls', 'Animal Collective', 2009, 'Merriweather Post Pavilion', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Sexy Boy', 'Air', 1997, 'Moon Safari', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Space Oddity', 'Дэвид Боуи', 1969, 'Space Oddity', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Oliver’s Army', 'Elvis Costello and the Attractions', 1979, 'Armed Forces', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Still D.R.E.', 'Dr. Dre', 1999, '2001', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Come On Eileen', 'Dexys Midnight Runners', 1982, 'Too-Rye-Ay', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'This Is Hardcore', 'Pulp', 1998, 'This Is Hardcore', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Got Your Money', 'Ol’ Dirty Bastard', 1999, 'Nigga Please', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Sea Within a Sea', 'The Horrors', 2009, 'Primary Colours', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Feel Good Hit of the Summer', 'Queens of the Stone Age', 2000, 'Rated R', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Walk This Way', 'Run-D.M.C.', 1986, 'Raising Hell', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Waterfalls', 'TLC', 1995, 'CrazySexyCool', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Sexx Laws', 'Бек', 1999, 'Midnite Vultures', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Born Slippy .NUXX', 'Underworld', 1996, 'Trainspotting', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Music Sounds Better with You', 'Stardust', 1998, '', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Hound Dog', 'Элвис Пресли', 1956, 'Elvis’ Golden Records', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Paperback Writer', 'The Beatles', 1966, 'A Collection of Beatles Oldies', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Empire State of Mind', 'Jay-Z', 2009, 'The Blueprint 3', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Shake Your Body (Down to the Ground)', 'The Jacksons', 1978, 'Destiny', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Trash', 'Suede', 1996, 'Coming Up', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Only Love Can Break Your Heart', 'Saint Etienne', 1990, 'Foxbase Alpha', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Perfect Day', 'Лу Рид', 1972, 'Transformer', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'My Sweet Lord', 'Джордж Харрисон', 1970, 'All Things Must Pass', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'You Love Us', 'Manic Street Preachers', 1992, 'Generation Terrorists', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Hallelujah', 'Happy Mondays', 1989, 'Hallelujah', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Leave Them All Behind', 'Ride', 1992, 'Going Black Again', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Reach Out I’ll Be There', 'Four Tops', 1966, 'Reach Out', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Little Fluffy Clouds', 'The Orb', 1990, 'The Orb’s Adventures Beyond the Ultraworld', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'My Name Is', 'Эминем', 1999, 'The Slim Shady LP', 'Rap');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Tangled Up in Blue', 'Боб Дилан', 1975, 'Blood on the Tracks', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Hounds of Love', 'Кейт Буш', 1985, 'Hounds of Love', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Velouria', 'Pixies', 1990, 'Bossanova', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'She Loves You', 'The Beatles', 1963, 'The Beatles’ Second Album', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'One Day Like This', 'Elbow', 2008, 'The Seldom Seen Kid', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Connnection', 'Elastica', 1994, 'Elastica', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Bigmouth Strikes Again', 'The Smiths', 1986, 'The Queen Is Dead', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Caught by the Fuzz', 'Supergrass', 1994, 'I Should Coco', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Crimewave', 'Crystal Castles', 2007, 'Crystal Castles', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Band on the Run', 'Wings', 1973, 'Band on the Run', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Get Lucky', 'Daft Punk', 2013, 'Random Access Memories', 'Electronic');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'It’s a Man’s Man’s Man’s World', 'Джеймс Браун', 1966, 'It’s a Man’s Man’s Man’s World', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Rebellion (Lies)', 'Arcade Fire', 2005, 'Funeral', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Daddy’s Gone', 'Glasvegas', 2007, 'Glasvegas', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Shipbuilding', 'Роберт Уайетт', 1982, 'Nothing Can Stop Us', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Mr. Blue Sky', 'Electric Light Orchestra', 1977, 'Out of the Blue', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'For Lovers', 'Wolfman при участии Питера Доэрти', 2004, '', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Family Affair', 'Sly and the Family Stone', 1971, 'There’s a Riot Goin’ On', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Fashion', 'Дэвид Боуи', 1980, 'Scary Monsters (and Super Creeps)', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'You Can’t Always Get What You Want', 'The Rolling Stones', 1969, 'Let It Bleed', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'The Words That Maketh Murder', 'Пи Джей Харви', 2011, 'Let England Shake', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Jump Around', 'House of Pain', 1992, 'House of Pain', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Crash', 'The Primitives', 1988, 'Lovely', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, '20th Century Boy', 'T. Rex', 1973, 'Hits!  The Very Best of T. Rex', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Enjoy the Silence', 'Depeche Mode', 1990, 'Violator', 'Rock');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Fake Plastic Trees', 'Radiohead', 1995, 'The Bends', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Suzanne', 'Леонард Коэн', 1967, 'Songs of Leonard Cohen', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Something', 'The Beatles', 1969, 'Abbey Road', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Tainted Love', 'Глория Джонс', 1964, '', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Beetlebum', 'Blur', 1996, 'Blur', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Going Underground', 'The Jam', 1980, 'Greatest Hits', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Spanish Sahara', 'Foals', 2010, 'Total Life Forever', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Outdoor Miner', 'Wire', 1978, 'Chairs Missing', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Papa Was a Rollin’ Stone', 'The Temptations', 1972, 'All Directions', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Ticket to Ride', 'The Beatles', 1965, 'Help!', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'History', 'The Verve', 1995, 'A Northern Soul', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, '1999', 'Принс', 1982, '1999', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Kick Out the Jams', 'MC5', 1969, 'Kick Out the Jams', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'All Along the Watchtower', 'The Jimi Hendrix Experience', 1968, 'Electric Ladyland', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Here', 'Pavement', 1992, 'Slanted and Enchanted', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Zero', 'Yeah Yeah Yeahs', 2009, 'It’s Blitz!', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Ring of Fire', 'Джонни Кэш', 1963, 'Ring of Fire: The Best of Johnny Cash', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'One Nation Under a Groove', 'Funkadelic', 1978, 'One Nation Under a Groove', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Brimful of Asha', 'Cornershop', 1997, 'When I Was Born for the 7th Time', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Itchycoo Park', 'Small Faces', 1967, 'There Are But Four Small Faces', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Big Time Sensuality', 'Бьорк', 1993, 'Debut', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Personal Jesus', 'Depeche Mode', 1990, 'Violator', 'Rock');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Destroy the Heart', 'The House of Love', 1990, 'The House of Love', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Strange Fruit', 'Билли Холидей', 1939, 'Lady Sings the Blues', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Sexual Healing', 'Марвин Гэй', 1982, 'Midnight Love', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Man in the Mirror', 'Майкл Джексон', 1988, 'Bad', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'My Favourite Dress', 'The Wedding Present', 1987, 'George Best', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Two Steps, Twice', 'Foals', 2008, 'Antidotes', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Novocaine for the Soul', 'Eels', 1996, 'Beautiful Freak', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Karmacoma', 'Massive Attack', 1995, 'Protection', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Rave On!', 'Бадди Холли', 1958, 'Buddy Holly', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Go West', 'Pet Shop Boys', 1993, 'Very', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'She Bangs the Drums', 'The Stone Roses', 1989, 'The Stone Roses', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'The Man Don’t Give a Fuck', 'Super Furry Animals', 1996, 'Out Spaced', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Come Together', 'The Beatles', 1969, 'Abbey Road', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'All Day and All of the Night', 'The Kinks', 1964, 'Kinks-Size', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Dare', 'Gorillaz', 2005, 'Demon Days', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Because the Night', 'Патти Смит', 1978, 'Easter', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Stan', 'Эминем', 2000, 'The Marshall Mathers LP', 'Rap');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Caught out There', 'Келис', 2000, 'Kaleidoscope', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Club Foot', 'Kasabian', 2004, 'Kasabian', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'California Dreamin’', 'The Mamas & the Papas', 1965, 'If You Can Believe Your Eyes and Ears', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Runaway', 'Канье Уэст при участии Pusha T', 2010, 'My Beautiful Dark Twisted Fantasy', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Fluorescent Adolescent', 'Arctic Monkeys', 2007, 'Favourite Worst Nightmare', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Only You', 'Yazoo', 1982, 'Upstairs at Eric’s', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Clint Eastwood', 'Gorillaz', 2001, 'Gorillaz', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Eight Miles High', 'The Byrds', 1966, 'Fifth Dimension', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Just Can’t Get Enough', 'Depeche Mode', 1981, 'Speak & Spell', 'Rock');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Rehab', 'Эми Уайнхаус', 2006, 'Back to Black', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Float On', 'Modest Mouse', 2004, 'Good News for People Who Love Bad News', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'The Boxer', 'Simon & Garfunkel', 1970, 'Bridge over Troubled Water', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Hey Boy Hey Girl', 'The Chemical Brothers', 1999, 'Surrender', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Loser', 'Бек', 1993, 'Mellow Gold', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Millionaire', 'Келис', 2004, 'Tasty', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Close to Me', 'The Cure', 1985, 'The Head on the Door', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'The Sun Ain’t Gonna Shine (Anymore)', 'The Walker Brothers', 1966, 'The Sun Ain’t Gonna Shine Anymore', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Sex & Drugs & Rock & Roll', 'Иэн Дьюри', 1977, 'New Boots and Panties!!', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'For Tomorrow', 'Blur', 1993, 'Modern Life Is Rubbish', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Pictures of You', 'The Cure', 1989, 'Disintegration', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Paid in Full', 'Eric B. & Rakim', 1987, 'Paid in Full', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Enter Sandman', 'Metallica', 1991, 'Metallica', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Bad Moon Rising', 'Creedence Clearwater Revival', 1969, 'Green River', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Killing of a Flashboy', 'Suede', 1994, 'Sci-Fi Lullabies', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Teen Age Riot', 'Sonic Youth', 1988, 'Daydream Nation', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Friday I’m in Love', 'The Cure', 1992, 'Wish', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Voodoo Ray', 'A Guy Called Gerald', 1988, 'Hot Lemonade', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'You Made Me Realise', 'My Bloody Valentine', 1988, 'You Made Me Realise', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Half the World Away', 'Oasis', 1994, 'The Masterplan', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'The Wild Ones', 'Suede', 1994, 'Dog Man Star', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Hyperballad', 'Бьорк', 1996, 'Post', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Don’t Believe the Hype', 'Public Enemy', 1988, 'It Takes a Nation of Millions to Hold Us Back', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Brianstorm', 'Arctic Monkeys', 2007, 'Favourite Worst Nightmare', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Love Action (I Believe in Love)', 'The Human League', 1981, 'Dare', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Don’t Stop ’Til You Get Enough', 'Майкл Джексон', 1979, 'Off the Wall', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Roadrunner', 'The Modern Lovers', 1976, 'The Modern Lovers', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Bennie and the Jets', 'Элтон Джон', 1973, 'Goodbye Yellow Brick Road', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Where the Wild Roses Grow', 'Nick Cave and the Bad Seeds и Кайли Миноуг', 1995, 'Murder Ballads', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'I’ll Feel a Whole Lot Better', 'The Byrds', 1965, 'Mr. Tambourine Man', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Piledriver Waltz', 'Arctic Monkeys', 2011, 'Suck It and See', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Kids', 'MGMT', 2007, 'Oracular Spectacular', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'While My Guitar Gently Weeps', 'The Beatles', 1968, 'The Beatles', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Lapdance', 'NERD', 2001, 'In Search Of...', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Typical Girls', 'The Slits', 1979, 'Cut', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Champagne Supernova', 'Oasis', 1995, '(What’s the Story) Morning Glory?', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Cut Your Hair', 'Pavement', 1991, 'Crooked Rain, Crooked Rain', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Oh, Pretty Woman', 'Пол Саймон', 1964, 'Orbisongs', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'The Boy with the Thorn in His Side', 'The Smiths', 1985, 'The Queen Is Dead', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'There’s No Other Way', 'Blur', 1991, 'Leisure', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Me and Julio Down by the Schoolyard', 'Пол Саймон', 1972, 'Paul Simon', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Paranoid', 'Black Sabbath', 1977, 'Paranoid', 'Rock');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'I Feel for You', 'Чака Хан', 1984, 'I Feel for You', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'To The End', 'Blur', 1994, 'Parklife', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'No More Heroes', 'The Stranglers', 1977, 'No More Heroes', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Sheila', 'Джейми Ти', 2006, 'Panic Prevention', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'The Real Slim Shady', 'Эминем', 2000, 'The Marshall Mathers LP', 'Rap');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'The Mercy Seat', 'Nick Cave and the Bad Seeds', 1988, 'Tender Prey', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Us', 'Регина Спектор', 2004, 'Soviet Kitsch', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Slide Away', 'Oasis', 1994, 'Definitely Maybe', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Learn to Fly', 'Foo Fighters', 1999, 'There Is Nothing Left to Lose', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Television, the Drug of the Nation', 'The Disposable Heroes of Hiphoprisy', 1991, 'Hypocrisy Is the Greatest Luxury', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'The Boys Are Back in Town', 'Thin Lizzy', 1976, 'Jailbreak', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Reverend Black Grape', 'Black Grape', 1995, 'It’s Great When You’re Straight... Yeah', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Where the Streets Have No Name', 'U2', 1987, 'The Joshua Tree', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Bad Girls', 'M.I.A.', 2012, 'Matangi', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Breezeblocks', 'Alt-J', 2012, 'An Awesome Wave', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Sheena Is a Punk Rocker', 'The Ramones', 1977, 'Rocket to Russia', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Fake Tales of San Francisco', 'Arctic Monkeys', 2005, 'Whatever People Say I Am, That’s What I’m Not', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Baby, I Love You', 'The Ronettes', 1963, 'Presenting the Fabulous Ronettes', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Hurt', 'Nine Inch Nails', 1994, 'The Downward Spiral', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Watching the Detectives', 'Fugazi', 1988, 'Fugazi', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Paris', 'Friendly Fires', 2007, 'Friendly Fires', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Watching the Detectives', 'Elvis Costello and the Attractions', 1977, 'My Aim is True', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Another Girl, Another Planet', 'The Only Ones', 1978, 'The Only Ones', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'You’re So Vain', 'Карли Саймон', 1972, 'No Secrets', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'For Tomorrow', 'Blur', 1993, 'Modern Life Is Rubbish', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Start!', 'Tindersticks', 1993, 'Sound Affects', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Come as You Are', 'Nirvana', 1991, 'Nevermind', 'Grunge');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Start!', 'The Jam', 1980, 'Sound Affects', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Yellow', 'Coldplay', 2000, 'Parachutes', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Holland, 1945', 'Neutral Milk Hotel', 1998, 'In the Aeroplane Over the Sea', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'The Book of Love', 'The Magnetic Fields', 1999, '69 Love Songs', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Paradise City', 'Guns N’ Roses', 1987, 'Appetite for Destruction', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Down by the Water', 'Пи Джей Харви', 1995, 'To Bring You My Love', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Plug In Baby', 'Muse', 2001, 'Origin of Symmetry', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Elephant', 'Tame Impala', 2012, 'Lonerism', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Hate to Say I Told You So', 'The Hives', 2000, 'Veni Vidi Vicious', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Golden Years', 'Дэвид Боуи', 1975, 'Station to Station', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Buddy Holly', 'Weezer', 1994, 'Weezer', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Uptown Top Ranking', 'Althea & Donna', 1977, 'Uptown Top Ranking', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Shame, Shame, Shame', 'Shirley & Company', 1974, 'Shame, Shame, Shame', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'The Drugs Don’t Work', 'The Verve', 1997, 'Urban Hymns', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'One Armed Scissor', 'At the Drive-In', 2000, 'Relationship of Command', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Sunny Afternoon', 'The Kinks', 1966, 'Face to Face', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'R U Mine?', 'Arctic Monkeys', 2012, 'AM', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'The Bucket', 'Kings of Leon', 2004, 'Aha Shake Heartbreak', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Free Nelson Mandela', 'The Specials', 1984, 'In the Studio', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Material Girl', 'Мадонна', 1984, 'Like a Virgin', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Pills And Soap', 'The Imposter', 1983, 'Punch the Clock', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Where It’s At', 'Бек', 1996, 'Odelay', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'I Fought the Law', 'The Bobby Fuller Four', 1965, 'I Fought the Law', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Witness (1 Hope)', 'Рутс Манува', 2001, 'Run Come Save Me', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Sorted for E’s & Wizz', 'Pulp', 1995, 'Different Class', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Open Up', 'Leftfield', 1993, 'Leftism', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'End of a Century', 'Blur', 1992, 'Midlife: A Beginner’s Guide to Blur', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Tumbling Dice', 'The Rolling Stones', 1972, 'Exile on Main St.', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Do You Remember the First Time?', 'Pulp', 1994, 'His ’n’ Hers', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'The Scientist', 'Coldplay', 2002, 'A Rush of Blood to the Head', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'A New England', 'Билли Брэгг', 1983, 'Life’s a Riot with Spy Vs Spy', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'I Am the Walrus', 'The Beatles', 1967, 'Magical Mystery Tour', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Setting Sun', 'The Chemical Brothers при участии Ноэла Галлахера', 1996, 'Dig Your Own Hole', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Whole Lotta Love', 'Led Zeppelin', 1969, 'Led Zeppelin II', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Town Called Malice', 'The Jam', 1982, 'The Gift', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Race for the Prize', 'The Flaming Lips', 1999, 'The Soft Bulletin', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'One Way or Another', 'Blondie', 1978, 'Parallel Lines', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'What’s My Name?', 'Snoop Dogg', 1993, 'Doggystyle', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Firestarter', 'The Prodigy', 1996, 'The Fat Of The Land', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Umbrella', 'Рианна', 2007, 'Good Girl Gone Bad', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Lust for Life', 'Игги Поп', 1977, 'Lust for Life', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'It’s the End of the World as We Know It (And I Feel Fine)', 'R.E.M.', 1987, 'Document', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Live and Let Die', 'Wings', 1973, 'Band on the Run', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'If You Wanna', 'The Vaccines', 2011, 'What Did You Expect from The Vaccines?', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'I Will Survive', 'Глория Гейнор', 1978, 'Love Tracks', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'About a Girl', 'Nirvana', 1989, 'Bleach', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Goddess on a Hiway', 'Mercury Rev', 1998, 'Deserter’s Songs', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Push It', 'Salt-n-Pepa', 1987, 'Hot, Cool & Vicious', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Star Sign', 'Teenage Fanclub', 1991, 'Bandwagonesque', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Dreaming of You', 'The Coral', 2002, 'The Coral', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Bloodbuzz Ohio', 'The National', 2010, 'High Violet', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Movin’ on Up', 'Primal Scream', 1991, 'Screamadelica', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Sweet Child o’ Mine', 'Guns N’ Roses', 1987, 'Appetite for Destruction', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Best of Friends', 'Palma Violets', 2012, '180', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Lola', 'The Kinks', 1970, 'Lola Versus Powerman and the Moneygoround, Part One', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Disarm', 'The Smashing Pumpkins', 1993, 'Siamese Dream', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Crazy', 'Gnarls Barkley', 2006, 'St. Elsewhere', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Imagine', 'Джон Леннон', 1971, 'Imagine', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Nuthin’ But a “G” Thang', 'Dr. Dre', 1993, 'The Chronic', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Highway to Hell', 'AC/DC', 1979, 'Highway to Hell', 'Rock');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Wouldn’t It Be Nice', 'The Beach Boys', 1966, 'Pet Sounds', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Ziggy Stardust', 'Дэвид Боуи', 1972, 'The Rise and Fall of Ziggy Stardust and the Spiders from Mars', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'The Killing Moon', 'Echo & the Bunnymen', 1984, 'Ocean Rain', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Darts of Pleasure', 'Franz Ferdinand', 2003, 'Franz Ferdinand', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Come to Daddy', 'Aphex Twin', 1997, 'Come to Daddy', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Some Might Say', 'Oasis', 1995, '(What’s the Story) Morning Glory?', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Starman', 'Дэвид Боуи', 1972, 'The Rise and Fall of Ziggy Stardust and the Spiders from Mars', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Across 110th Street', 'Бобби Уомак', 1972, 'Across 110th Street Soundtrack', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Suedehead', 'Моррисси', 1988, 'Viva Hate', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Golden Brown', 'The Stranglers', 1981, 'La Folie', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Red Right Hand', 'Nick Cave and the Bad Seeds', 1994, 'Let Love In', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Riders on the Storm', 'The Doors', 1971, 'L.A. Woman', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'One', 'Джонни Кэш', 2000, 'American III: Solitary Man', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'New York City Cops', 'The Strokes', 2001, 'Is This It', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Overload', 'Sugababes', 2000, 'One Touch', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Everybody Hurts', 'R.E.M.', 1992, 'Automatic for the People', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Patio Song', 'Gorky\'s Zygotic Mynci', 1996, 'Are You Experienced', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Hey Joe', 'The Jimi Hendrix Experience', 1966, 'Are You Experienced', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Kill All Hippies', 'Primal Scream', 2000, 'XTRMNTR', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Girl from Mars', 'Ash', 1995, '1977', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Out of Time', 'Blur', 2003, 'Think Tank', '');
INSERT INTO `db_1`.`all` (`id`, `composition`, `artist`, `date`, `album`, `genre`) VALUES (DEFAULT, 'Five Years', 'Дэвид Боуи', 1972, 'The Rise and Fall of Ziggy Stardust and the Spiders from Mars', '');

COMMIT;

